name: esky
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  freezed_annotation:
  

dev_dependencies:
  build_runner:
  freezed: ^0.10.9
  pedantic: ^1.9.0
  test: ^1.6.0
